/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CitadelBackgroundPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  enableStars: true,
  enableNebula: true,
  enableAurora: false,
  enableGalaxies: true,
  enableFog: true,
  enableDust: true,
  starDensity: 150,
  // Increased default because we split into two layers
  enableAutoPerf: true
};
var CitadelSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Infinite Citadel Environment Engine" });
    new import_obsidian.Setting(containerEl).setName("Enable Starfield Engine").setDesc("Render procedural twinkling star particles on 2D Canvas.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableStars).onChange(async (value) => {
        var _a;
        this.plugin.settings.enableStars = value;
        await this.plugin.saveSettings();
        (_a = this.plugin.canvasManager) == null ? void 0 : _a.updateSettings(this.plugin.settings);
      })
    );
    new import_obsidian.Setting(containerEl).setName("Enable Distant Galaxies").setDesc("Render deep-space star clusters.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableGalaxies).onChange(async (value) => {
        var _a;
        this.plugin.settings.enableGalaxies = value;
        await this.plugin.saveSettings();
        (_a = this.plugin.canvasManager) == null ? void 0 : _a.updateSettings(this.plugin.settings);
      })
    );
    new import_obsidian.Setting(containerEl).setName("Enable Nebula Gas").setDesc("Render massive, slow-moving interstellar clouds.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableNebula).onChange(async (value) => {
        var _a;
        this.plugin.settings.enableNebula = value;
        await this.plugin.saveSettings();
        (_a = this.plugin.canvasManager) == null ? void 0 : _a.updateSettings(this.plugin.settings);
      })
    );
    new import_obsidian.Setting(containerEl).setName("Enable Volumetric Fog").setDesc("Render low-hanging atmospheric fog.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableFog).onChange(async (value) => {
        var _a;
        this.plugin.settings.enableFog = value;
        await this.plugin.saveSettings();
        (_a = this.plugin.canvasManager) == null ? void 0 : _a.updateSettings(this.plugin.settings);
      })
    );
    new import_obsidian.Setting(containerEl).setName("Enable Ambient Dust").setDesc("Render out-of-focus, fast-moving foreground particles.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableDust).onChange(async (value) => {
        var _a;
        this.plugin.settings.enableDust = value;
        await this.plugin.saveSettings();
        (_a = this.plugin.canvasManager) == null ? void 0 : _a.updateSettings(this.plugin.settings);
      })
    );
    new import_obsidian.Setting(containerEl).setName("Star Density").setDesc("Number of star particles drawn per frame (10 to 400).").addSlider(
      (slider) => slider.setLimits(10, 400, 10).setValue(this.plugin.settings.starDensity).setDynamicTooltip().onChange(async (value) => {
        var _a;
        this.plugin.settings.starDensity = value;
        await this.plugin.saveSettings();
        (_a = this.plugin.canvasManager) == null ? void 0 : _a.updateSettings(this.plugin.settings);
      })
    );
    new import_obsidian.Setting(containerEl).setName("Adaptive Performance Guard").setDesc("Automatically reduce particle count if frame rate drops below 45 FPS.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableAutoPerf).onChange(async (value) => {
        this.plugin.settings.enableAutoPerf = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/canvas/layers/starfield.ts
var StarfieldLayer = class {
  constructor(count) {
    this.stars = [];
    this.width = 0;
    this.height = 0;
    this.count = count;
  }
  resize(w, h) {
    this.width = w;
    this.height = h;
    this.initStars(this.count);
  }
  setCount(count) {
    this.count = count;
    this.initStars(count);
  }
  initStars(count) {
    this.stars = [];
    for (let i = 0; i < count; i++) {
      const isForeground = Math.random() > 0.8;
      this.stars.push({
        x: Math.random() * (this.width || window.innerWidth || 1920),
        y: Math.random() * (this.height || window.innerHeight || 1080),
        size: isForeground ? Math.random() * 1.5 + 1 : Math.random() * 0.8 + 0.2,
        alpha: Math.random(),
        speed: Math.random() * 0.02 + 5e-3,
        phase: Math.random() * Math.PI * 2,
        parallax: isForeground ? 0.05 : 0.01
      });
    }
  }
  render(ctx, isThrottled, time) {
    ctx.save();
    ctx.fillStyle = "#ffffff";
    const drawCount = isThrottled ? Math.floor(this.stars.length / 2) : this.stars.length;
    for (let i = 0; i < drawCount; i++) {
      const star = this.stars[i];
      star.phase += star.speed;
      let x = star.x - time * star.parallax;
      x = (x % this.width + this.width) % this.width;
      const opacity = (Math.sin(star.phase) + 1) / 2 * 0.7 + 0.1;
      ctx.globalAlpha = opacity;
      ctx.beginPath();
      ctx.arc(x, star.y, star.size, 0, Math.PI * 2);
      ctx.fill();
    }
    ctx.restore();
  }
  destroy() {
    this.stars = [];
  }
};

// src/canvas/layers/distantGalaxies.ts
var DistantGalaxiesLayer = class {
  constructor() {
    this.galaxies = [];
    this.width = 0;
    this.height = 0;
  }
  resize(w, h) {
    this.width = w;
    this.height = h;
    this.initGalaxies();
  }
  initGalaxies() {
    this.galaxies = [];
    const count = 3;
    const colors = ["rgba(155, 107, 242, ", "rgba(85, 230, 236, ", "rgba(217, 168, 87, "];
    for (let i = 0; i < count; i++) {
      const numParticles = 80;
      const particles = [];
      for (let p = 0; p < numParticles; p++) {
        const angle = Math.random() * Math.PI * 2;
        const dist = Math.random() * Math.random() * 300;
        particles.push({
          dx: Math.cos(angle) * dist * 1.5,
          dy: Math.sin(angle) * dist * 0.5,
          size: Math.random() * 1.5 + 0.5,
          alpha: Math.random() * 0.3 + 0.1
        });
      }
      this.galaxies.push({
        x: Math.random() * this.width,
        y: Math.random() * this.height,
        radius: 300,
        color: colors[i % colors.length],
        particles,
        parallax: Math.random() * 5e-3 + 2e-3
        // Extremely slow moving
      });
    }
  }
  render(ctx, isThrottled, time) {
    if (isThrottled)
      return;
    ctx.save();
    for (const galaxy of this.galaxies) {
      let x = galaxy.x - time * galaxy.parallax;
      x = (x % (this.width + 1e3) + (this.width + 1e3)) % (this.width + 1e3) - 500;
      for (const p of galaxy.particles) {
        ctx.fillStyle = `${galaxy.color}${p.alpha})`;
        ctx.beginPath();
        ctx.arc(x + p.dx, galaxy.y + p.dy, p.size, 0, Math.PI * 2);
        ctx.fill();
      }
    }
    ctx.restore();
  }
  destroy() {
    this.galaxies = [];
  }
};

// src/canvas/layers/nebula.ts
var NebulaLayer = class {
  constructor() {
    this.clouds = [];
    this.width = 0;
    this.height = 0;
  }
  resize(w, h) {
    this.width = w;
    this.height = h;
    this.initClouds();
  }
  initClouds() {
    this.clouds = [];
    const colors = [
      "rgba(85, 230, 236, ",
      // Cyan
      "rgba(155, 107, 242, ",
      // Purple
      "rgba(43, 143, 150, "
      // Deep Cyan
    ];
    const count = 4;
    for (let i = 0; i < count; i++) {
      this.clouds.push({
        x: Math.random() * (this.width + 1e3) - 500,
        y: Math.random() * this.height,
        radius: Math.random() * 600 + 400,
        // Very large clouds
        color: colors[i % colors.length],
        parallax: Math.random() * 0.01 + 5e-3,
        pulseSpeed: Math.random() * 5e-3 + 1e-3,
        phase: Math.random() * Math.PI * 2
      });
    }
  }
  render(ctx, isThrottled, time) {
    if (isThrottled)
      return;
    ctx.save();
    ctx.globalCompositeOperation = "screen";
    for (const cloud of this.clouds) {
      let x = cloud.x - time * cloud.parallax;
      x = (x % (this.width + 2e3) + (this.width + 2e3)) % (this.width + 2e3) - 1e3;
      cloud.phase += cloud.pulseSpeed;
      const opacity = (Math.sin(cloud.phase) + 1) / 2 * 0.04 + 0.02;
      const gradient = ctx.createRadialGradient(x, cloud.y, 0, x, cloud.y, cloud.radius);
      gradient.addColorStop(0, `${cloud.color}${opacity})`);
      gradient.addColorStop(0.5, `${cloud.color}${opacity * 0.5})`);
      gradient.addColorStop(1, `${cloud.color}0)`);
      ctx.fillStyle = gradient;
      ctx.beginPath();
      ctx.arc(x, cloud.y, cloud.radius, 0, Math.PI * 2);
      ctx.fill();
    }
    ctx.restore();
  }
  destroy() {
    this.clouds = [];
  }
};

// src/canvas/layers/volumetricFog.ts
var VolumetricFogLayer = class {
  constructor() {
    this.clouds = [];
    this.width = 0;
    this.height = 0;
  }
  resize(w, h) {
    this.width = w;
    this.height = h;
    this.initClouds();
  }
  initClouds() {
    this.clouds = [];
    const count = 5;
    for (let i = 0; i < count; i++) {
      this.clouds.push({
        x: Math.random() * this.width,
        y: this.height - Math.random() * this.height * 0.4,
        // Keep mostly lower half
        width: Math.random() * 800 + 400,
        height: Math.random() * 300 + 150,
        speed: Math.random() * 0.2 + 0.05,
        opacity: Math.random() * 0.03 + 0.01
        // Very faint
      });
    }
  }
  render(ctx, isThrottled, time) {
    if (isThrottled)
      return;
    ctx.save();
    ctx.globalCompositeOperation = "screen";
    for (const cloud of this.clouds) {
      let x = cloud.x + time * cloud.speed;
      x = (x % (this.width + cloud.width) + (this.width + cloud.width)) % (this.width + cloud.width) - cloud.width;
      const gradient = ctx.createRadialGradient(x, cloud.y, 0, x, cloud.y, cloud.width / 2);
      gradient.addColorStop(0, `rgba(43, 143, 150, ${cloud.opacity})`);
      gradient.addColorStop(1, `rgba(43, 143, 150, 0)`);
      ctx.fillStyle = gradient;
      ctx.beginPath();
      ctx.ellipse(x, cloud.y, cloud.width / 2, cloud.height / 2, 0, 0, Math.PI * 2);
      ctx.fill();
    }
    ctx.restore();
  }
  destroy() {
    this.clouds = [];
  }
};

// src/canvas/layers/dust.ts
var DustLayer = class {
  constructor() {
    this.motes = [];
    this.width = 0;
    this.height = 0;
  }
  resize(w, h) {
    this.width = w;
    this.height = h;
    this.initMotes();
  }
  initMotes() {
    this.motes = [];
    const count = 30;
    for (let i = 0; i < count; i++) {
      this.motes.push({
        x: Math.random() * this.width,
        y: Math.random() * this.height,
        size: Math.random() * 4 + 2,
        // Larger than stars
        alpha: Math.random() * 0.15 + 0.05,
        // Quite faint
        // Fast parallax to simulate extreme foreground
        parallaxX: (Math.random() - 0.5) * 0.1,
        parallaxY: Math.random() * -0.05 - 0.02,
        // Drifting upwards slightly
        phase: Math.random() * Math.PI * 2
      });
    }
  }
  render(ctx, isThrottled, time) {
    if (isThrottled)
      return;
    ctx.save();
    ctx.fillStyle = "#d9a857";
    ctx.filter = "blur(2px)";
    for (const mote of this.motes) {
      let x = mote.x + time * mote.parallaxX;
      let y = mote.y + time * mote.parallaxY;
      x = (x % this.width + this.width) % this.width;
      y = (y % this.height + this.height) % this.height;
      mote.phase += 0.01;
      const opacity = (Math.sin(mote.phase) + 1) / 2 * mote.alpha;
      ctx.globalAlpha = opacity;
      ctx.beginPath();
      ctx.arc(x, y, mote.size, 0, Math.PI * 2);
      ctx.fill();
    }
    ctx.restore();
  }
  destroy() {
    this.motes = [];
  }
};

// src/utils/perf.ts
var PerformanceMonitor = class {
  constructor() {
    this.frameTimes = [];
    this.maxBuffer = 60;
    this.lastTime = performance.now();
    this.isThrottled = false;
  }
  tick() {
    const now = performance.now();
    const delta = now - this.lastTime;
    this.lastTime = now;
    this.frameTimes.push(delta);
    if (this.frameTimes.length > this.maxBuffer) {
      this.frameTimes.shift();
    }
    const avgFrameTime = this.frameTimes.reduce((a, b) => a + b, 0) / this.frameTimes.length;
    const fps = 1e3 / avgFrameTime;
    const shouldThrottle = fps < 45 && this.frameTimes.length >= 30;
    if (shouldThrottle !== this.isThrottled) {
      this.isThrottled = shouldThrottle;
      if (this.isThrottled) {
        document.body.setAttribute("data-citadel-perf", "low");
      } else {
        document.body.removeAttribute("data-citadel-perf");
      }
    }
    return this.isThrottled;
  }
  getThrottled() {
    return this.isThrottled;
  }
};

// src/canvas/background.ts
var CanvasManager = class {
  constructor(parentEl, settings) {
    this.animFrameId = null;
    this.isVisible = true;
    this.time = 0;
    this.loop = () => {
      if (!this.isVisible)
        return;
      const isThrottled = this.settings.enableAutoPerf ? this.perfMonitor.tick() : false;
      this.time++;
      this.ctx.clearRect(0, 0, window.innerWidth, window.innerHeight);
      if (this.settings.enableGalaxies)
        this.galaxies.render(this.ctx, isThrottled, this.time);
      if (this.settings.enableNebula)
        this.nebula.render(this.ctx, isThrottled, this.time);
      if (this.settings.enableStars)
        this.starfield.render(this.ctx, isThrottled, this.time);
      if (this.settings.enableFog)
        this.fog.render(this.ctx, isThrottled, this.time);
      if (this.settings.enableDust)
        this.dust.render(this.ctx, isThrottled, this.time);
      this.animFrameId = requestAnimationFrame(this.loop);
    };
    this.parentEl = parentEl;
    this.settings = settings;
    this.canvas = document.createElement("canvas");
    this.canvas.className = "citadel-bg-canvas";
    Object.assign(this.canvas.style, {
      position: "fixed",
      top: "0",
      left: "0",
      width: "100vw",
      height: "100vh",
      pointerEvents: "none",
      zIndex: "0"
    });
    const context = this.canvas.getContext("2d");
    if (!context)
      throw new Error("Could not get 2D canvas context");
    this.ctx = context;
    this.perfMonitor = new PerformanceMonitor();
    this.starfield = new StarfieldLayer(this.settings.starDensity);
    this.galaxies = new DistantGalaxiesLayer();
    this.nebula = new NebulaLayer();
    this.fog = new VolumetricFogLayer();
    this.dust = new DustLayer();
    this.handleResize = this.handleResize.bind(this);
    this.handleVisibility = this.handleVisibility.bind(this);
  }
  start() {
    this.parentEl.appendChild(this.canvas);
    window.addEventListener("resize", this.handleResize);
    document.addEventListener("visibilitychange", this.handleVisibility);
    this.handleResize();
    this.loop();
  }
  updateSettings(newSettings) {
    this.settings = newSettings;
    this.starfield.setCount(this.settings.starDensity);
    this.handleResize();
  }
  handleResize() {
    const dpr = window.devicePixelRatio || 1;
    const w = window.innerWidth;
    const h = window.innerHeight;
    this.canvas.width = w * dpr;
    this.canvas.height = h * dpr;
    this.ctx.scale(dpr, dpr);
    this.starfield.resize(w, h);
    this.galaxies.resize(w, h);
    this.nebula.resize(w, h);
    this.fog.resize(w, h);
    this.dust.resize(w, h);
  }
  handleVisibility() {
    this.isVisible = document.visibilityState === "visible";
    if (this.isVisible && !this.animFrameId) {
      this.loop();
    }
  }
  destroy() {
    if (this.animFrameId) {
      cancelAnimationFrame(this.animFrameId);
    }
    window.removeEventListener("resize", this.handleResize);
    document.removeEventListener("visibilitychange", this.handleVisibility);
    this.starfield.destroy();
    this.galaxies.destroy();
    this.nebula.destroy();
    this.fog.destroy();
    this.dust.destroy();
    this.canvas.remove();
  }
};

// src/main.ts
var CitadelBackgroundPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.canvasManager = null;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new CitadelSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      this.initCanvas();
    });
  }
  initCanvas() {
    const container = document.body.querySelector(".app-container") || document.body;
    this.canvasManager = new CanvasManager(container, this.settings);
    this.canvasManager.start();
  }
  onunload() {
    if (this.canvasManager) {
      this.canvasManager.destroy();
      this.canvasManager = null;
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
